cabal-version: 3.0
name: assertica
version: 0.1.0.0
license: BSL-1.0
author: Ahmad Ali Parr
maintainer: ahmedparr93@gmail.com

common warnings
    ghc-options: -Wall -Wcompat -Wincomplete-record-updates
                 -Wincomplete-uni-patterns -Wredundant-constraints
                 -fno-warn-unticked-promoted-constructors

library
    import: warnings
    exposed-modules:
        Assertica.Core.AST
        Assertica.Core.Assertion
        Assertica.Core.Equality
        Assertica.Core.Invariants
        Assertica.Core.Module
        Assertica.Core.ModuleEnv
        Assertica.Core.TypeEnv
        Assertica.Core.TypeChecker
        Assertica.Core.ProofTerm
        Assertica.Core.Pattern
        Assertica.Core.Termination
        Assertica.Core.Positivity
        Assertica.Surface.AST
        Assertica.Surface.Lexer
        Assertica.Surface.Parser
        Assertica.Surface.Elaborator
        Assertica.Backend.CodeGen
        Assertica.Backend.TermCompiler
        Assertica.Backend.TypeCompiler
        Assertica.Backend.ProofCompiler
        Assertica.Backend.Emit
        Assertica.StdLib.Setoid
        Assertica.StdLib.Lattice
        Assertica.StdLib.Absorption
        Assertica.StdLib.Monomorphism
        Assertica.Verify.Pipeline
        Assertica.Verify.Report
        Assertica.Verify.ErrorReport
        Assertica.Verify.CI
        Assertica.Verify.CLI
    build-depends:
        base >=4.16 && <5,
        containers >=0.6,
        text >=1.2,
        mtl >=2.2,
        directory >=1.3,
        filepath >=1.4,
        time >=1.9
    hs-source-dirs: src
    default-language: Haskell2010

test-suite assertica-tests
    import: warnings
    type: exitcode-stdio-1.0
    main-is: Main.hs
    other-modules:
        Test.Core.AST
        Test.Core.Assertion
        Test.Core.Equality
        Test.Core.Invariants
        Test.Core.Module
        Test.Core.TypeChecker
        Test.Core.ProofTerm
        Test.Core.Termination
        Test.Core.Positivity
        Test.Core.Pattern
        Test.Surface.Lexer
        Test.Surface.Parser
        Test.Surface.Elaborator
        Test.Backend.CodeGen
        Test.Backend.TermCompiler
        Test.Backend.TypeCompiler
        Test.Backend.ProofCompiler
        Test.Backend.Emit
        Test.Backend.Integration
        Test.StdLib.Setoid
        Test.StdLib.Lattice
        Test.StdLib.Absorption
        Test.StdLib.Monomorphism
        Test.Verify.PipelineTests
        Test.Verify.ReportTests
        Test.Verify.CITests
        Test.Verify.ErrorReportTests
    build-depends:
        base >=4.16 && <5,
        assertica,
        containers >=0.6,
        text >=1.2,
        mtl >=2.2,
        tasty >=1.4,
        tasty-hunit >=0.10,
        tasty-quickcheck >=0.10,
        QuickCheck >=2.14
    hs-source-dirs: test
    default-language: Haskell2010
